In [1]:
import torch
a=torch.randint(1,5,(2,3))
b=torch.randint(1,5,(2,3))
print(a)
print(b)

tensor([[3, 4, 1],
        [4, 4, 2]])
tensor([[4, 3, 1],
        [3, 3, 2]])


In [2]:
a+b

tensor([[7, 7, 2],
        [7, 7, 4]])

In [3]:
torch.add(a,b)

tensor([[7, 7, 2],
        [7, 7, 4]])

In [5]:
result=torch.zeros(2,3)
torch.add(a,b,out=result)

tensor([[7., 7., 2.],
        [7., 7., 4.]])

In [6]:
#a+b
#任何使用张量tensor回发生变化的操作都有前缀'_'
a.add_(b)
a

tensor([[7, 7, 2],
        [7, 7, 4]])

In [9]:
a-b

tensor([[3, 4, 1],
        [4, 4, 2]])

In [10]:
a/b

tensor([[1.7500, 2.3333, 2.0000],
        [2.3333, 2.3333, 2.0000]])

In [11]:
a%b

tensor([[3, 1, 0],
        [1, 1, 0]])

In [12]:
a//b#取整

tensor([[1, 2, 2],
        [2, 2, 2]])

In [13]:
tensor=torch.ones(3,5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:
a

tensor([[7, 7, 2],
        [7, 7, 4]])

In [15]:
torch.matmul(a,tensor)

RuntimeError: expected scalar type Long but found Float

In [16]:
a.dtype

torch.int64

In [17]:
tensor.dtype

torch.float32

In [18]:
a=a.float()
a.dtype

torch.float32

In [19]:
torch.matmul(a,tensor)#乘法

tensor([[16., 16., 16., 16., 16.],
        [18., 18., 18., 18., 18.]])

In [20]:
a.T#转置

tensor([[7., 7.],
        [7., 7.],
        [2., 4.]])