In [4]:
import torch
torch.ones(2,3) #生成全为1 的矩阵
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.rand(3,4)#生成随机数

tensor([[0.9812, 0.4325, 0.2601, 0.3397],
        [0.1162, 0.3927, 0.5047, 0.8578],
        [0.5530, 0.6194, 0.1545, 0.1502]])

In [6]:
torch.randint(0,10,(3,4))

tensor([[9, 6, 1, 7],
        [3, 4, 3, 1],
        [0, 5, 5, 4]])

In [7]:
torch.randn(3,4)#正态分布的随机数

tensor([[ 1.1375, -0.2973, -1.0530, -0.8432],
        [-0.7294, -0.3093,  0.6227,  1.4519],
        [-0.3168, -1.0652,  0.4906, -1.3908]])

In [13]:
a=torch.tensor([[1,2],
                [3,4],
                [5,6]])
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [15]:
b=torch.rand_like(a,dtype=float)#形状一样，数据随机
b

tensor([[0.1363, 0.5792],
        [0.2963, 0.5690],
        [0.9428, 0.4346]], dtype=torch.float64)

In [16]:
print(b.size())#查看数据形状
print(b.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [17]:
c=b.view(6)#修改数据形状,相当于reshape
c

tensor([0.1363, 0.5792, 0.2963, 0.5690, 0.9428, 0.4346], dtype=torch.float64)

In [18]:
c[1]

tensor(0.5792, dtype=torch.float64)

In [19]:
c[1].item()#tesor变为python数值,只能修改一个值

0.5792091128493655

In [20]:
import numpy as np
np.array(c)

array([0.13628731, 0.57920911, 0.29633211, 0.5690317 , 0.94276514,
       0.43458822])

In [21]:
array=np.array([1,2,3])
array

array([1, 2, 3])

In [23]:
tensor=torch.tensor(array)
tensor

tensor([1, 2, 3], dtype=torch.int32)