In [2]:
import torch
tensor=torch.arange(2 ,14)#2-13生成这些数
print(tensor)

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])


In [3]:
print(tensor[-1])

tensor(13)


In [4]:
print(tensor[5:-1])#取到-1之前的数

tensor([ 7,  8,  9, 10, 11, 12])


In [5]:
index=[1,2,3,5,5]
print(tensor[index])

tensor([3, 4, 5, 7, 7])
